### ISSUE TITLE
Can auto-contrast functions be put in a package?

### ISSUE THREAD

**Issue by davidhodge931** [teunbrand/ggplot_tricks#2]
Hi @teunbrand, I think that your functions to create auto text contrast are really useful, and should be put into a package to make it more accessible. I could put them into my R package (ggblanket) and reference you? Or, alternatively, I could create a ggh4x issue and add a Pull Request?

**Comment by davidhodge931** [comment]
I basically want to make the autocontrast function exported with arguments for the light colour to use and the dark text colour to use - and the contrast function internal.

<img width="508" alt="image" src="https://github.com/teunbrand/ggplot_tricks/assets/55065152/52f6cf42-2e05-44b2-a3e1-daa017e0a959">

**Comment by davidhodge931** [comment]
I was thinking I would add an exported function called `aes_contrast` like below with some optional arg's for the light and dark colour. Then the user would just slice it into `geom_text(mapping = aes(..., !!!aes_contrast())`  
<img width="449" alt="image" src="https://github.com/teunbrand/ggplot_tricks/assets/55065152/45028e15-a72b-4452-a45b-214761efff5f">

**Comment by teunbrand** [comment]
Hi David, this repo has an MIT licence so you're pretty much at liberty to do with the code as you see fit. If you think this is a good fit for ggblanket, by all means, take the parts that you think are useful.

**Comment by davidhodge931** [comment]
Awesome, yeah I totally think it should go somewhere - it's too useful! I've already got 1 random vis helper in ggblanket, so one more will be fine.

Do you know how I can use roxygen to reference you in the function? I haven't done this before. I'm guessing the @references tag?? I'll also put a bullet point in the News referencing you. Also, should I use your name or github handle?

**Comment by davidhodge931** [comment]
Also, I'm assuming that ggplot will likely continue to support this method of splicing within aes?

As in, is this method likely to be ok for the future?
``` r
library(tidyverse)
library(palmerpenguins)
penguins |> 
  ggplot() +
  geom_point(aes(x = flipper_length_mm, !!!aes(y = body_mass_g)))
#> Warning: Removed 2 rows containing missing values or values outside the scale range
#> (`geom_point()`).
```

![](https://i.imgur.com/vbNZEm4.png)

<sup>Created on 2024-01-27 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>


Like ggplot are not likely to make a change to their code, such that this method won't work anymore? Just thinking as I noticed in your text that the method is undocumented by ggplot

**Comment by teunbrand** [comment]
Yeah I think the splicing should be pretty stable up to the point that {rlang} changes anything. We recently added `theme()` splicing as well, so there is no trend towards not splicing. The repo doesn't have a DOI or anything so I think you can refer to me or the repo however you see fit if at all. I don't require to be cited for this.

**Comment by davidhodge931** [comment]
Cool, just made an `aes_contrast` function where the light/dark colours can be adjusted by the user - and a couple of shortcut helpers that work nicely with my default themes. 
https://davidhodge931.github.io/ggblanket/reference/aes_contrast.html
https://davidhodge931.github.io/ggblanket/reference/aes_contrast_light_mode.html
https://davidhodge931.github.io/ggblanket/reference/aes_contrast_dark_mode.html

I think I'll add you in as a contributor to ggblanket using the below details from ggh4x (and remove the references from the function help), if you are okay with that? 

```
 person(given = "Teun",
           family = "van den Brand",
           role = c("ctb"),
           comment = c(ORCID = "0000-0002-9335-7468"))
```

**Comment by davidhodge931** [comment]
On reflection, I think I'll just follow ggplot's approach of referencing all contributors in the News, as otherwise it might get tricky in the future.

FYI, I settled on one exported function named `aes_contrast`  after going back and forth a lot. It has defaults that are close to black and white text colours that are optimsed for my themes. But you can change them to anything.

Planning on releasing as soon as ggplot does

Thanks heaps! Also, amazing work with this release of ggplot. It's a big release. So much useful stuff

**Comment by teunbrand** [comment]
That seems fair to me. 

> Planning on releasing as soon as ggplot does

I don't think the auto-contrast thingy would depend on dev-ggplot2, does it?
In any case, we plan to release next week, reverse dependency gods willing

**Comment by davidhodge931** [comment]
I think it should work for either the current version or the dev version.

That reverse dependency work you guys do looks freakily massive! 

Been looking forward to this release for a while :)

**Comment by teunbrand** [comment]
> Been looking forward to this release for a while :)

Me too, David, me too
